# Generated by Django 5.1.3 on 2024-11-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('actors', models.CharField(max_length=255)),
                ('types', models.CharField(max_length=255)),
                ('areas', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('intro', models.TextField()),
            ],
        ),
    ]
