# Generated by Django 5.1.3 on 2024-11-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_movie_delete_cloth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Cloth',
        ),
    ]
