# Generated by Django 5.1.3 on 2024-11-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_movie_cloth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='year',
            new_name='buytime',
        ),
        migrations.RenameField(
            model_name='cloth',
            old_name='actors',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='cloth',
            old_name='areas',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='cloth',
            old_name='types',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='cloth',
            old_name='rating',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='intro',
        ),
    ]
