# Generated by Django 5.1.3 on 2024-11-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_year_cloth_buytime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
