# Generated by Django 5.1.3 on 2024-11-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_cloth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='clothes_images/'),
        ),
    ]
