# Generated by Django 5.1.3 on 2024-11-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cloth_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='weather',
            field=models.CharField(default='晴', max_length=100),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='myapp/'),
        ),
    ]
